services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - .:/home/src
      - ${DATA_DIR}:/home/data
      - ${GOOGLE_CRED_LOCALPATH}:/home/src/geneditor_key.json:ro
    restart: on-failure:5